# Generated by Django 5.2.17 on 2026-09-21 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.CharField(max_length=64)),
                ('track_name', models.CharField(blank=True, max_length=255)),
                ('artist_name', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('play', 'Play'), ('like', 'Like'), ('skip', 'Skip')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='activity_user_created_idx'), models.Index(fields=['action', '-created_at'], name='activity_action_created_idx'), models.Index(fields=['artist_name'], name='activity_artist_idx'), models.Index(fields=['track_id'], name='activity_track_idx')],
            },
        ),
    ]
