# Generated by Django 5.2.17 on 2026-09-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='prefs_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
