# ruff: noqa: E501  — generated fixture data; long literal lines are intentional
"""
Indian fixture data for SPOTIFY_MOCK mode (real Spotify ids, market IN).

Generated from live search results so mock runs for the Indian demo profiles
look like live runs. Merged into the base fixture by mock_data.py.
"""

from .mock_data import _t

TRACKS_BY_GENRE_IN: dict[str, list[dict]] = {
    "bollywood": [
        _t(
            "6JcrLYDiRVA8aS25tDpjB3",
            "Kaise Basiya Bajaye",
            "Begum Akhtar",
            "Best of Begum Akhtar Ghazals Vol 1",
            0,
        ),
        _t("1Azaw6XEJV91faEaspkW5O", "Maine Baalam Se", "Geeta Dutt", "Aadhi Raat", 0),
        _t(
            "1xYediaRvLaG8FtLW4xEwz",
            "Aamar Hriday Tomar Aapon",
            "Kanan Devi",
            "Chirodiner Chironatun",
            0,
        ),
        _t("1MxSiCZRRnEpwwR01AqNUN", "Mane Pare", "Bappi Lahiri", "Ghum Asena", 0),
    ],
    "indian pop": [
        _t(
            "1z8zNYDPkeKmouJgPRwrOP",
            "Jr chhaks Suangtuahna",
            "Zorimawi",
            "Jr chhaks Suangtuahna",
            0,
        ),
        _t(
            "1xbjdcu0yk5dS08Va5s51R",
            "Jonathan Pachuau Rinawm biahthu kan tiam kha",
            "Zorimawi",
            "Jonathan Pachuau Rinawm biahthu kan tiam kha",
            0,
        ),
        _t(
            "01YFXgoeDxKJweIC0OdU5z",
            "Zohmingchhuangi a sawm che",
            "Zorimawi",
            "Zohmingchhuangi a sawm che",
            0,
        ),
        _t(
            "4y1PitpGVZR4NKwp8SiCED",
            "Moris Chhuk Chho (Gospel Rap)",
            "Zorimawi",
            "Moris Chhuk Chho (Gospel Rap)",
            0,
        ),
    ],
    "punjabi": [
        _t(
            "1KxjolcKAlMgvQn01VWUvt",
            "Shagan : Devin Ve Babula Oos Ghare",
            "Surinder Kaur",
            "Wadhaiyaan",
            0,
        ),
        _t(
            "1bpmFxK6hk2Fgpw4iCJq7Y",
            "Dhi Da Ni Dena Dola",
            "Kuldip Manak",
            "Heere Kachiye Jahan Diye",
            0,
        ),
        _t(
            "4A7bpdwEiVeV98OxbTiOwT",
            "Singh Rehnde Sada Chardi Kala",
            "Kuldeep Manak",
            "Singh Rehnde Sada Chardi Kala",
            0,
        ),
        _t(
            "7CwmIBiXenDPWf6VBK6AF5",
            "Eh Din Khushian De",
            "Mohinder Kaur Bhamra",
            "Songs for Punjabi Weddings (Songs & Ceremonies)",
            0,
        ),
    ],
    "bhangra": [
        _t(
            "3DZwd57fr7KbiVSvVOLYsk",
            "Bimari Pe Gaee",
            "Manmohan Waris",
            "Punjabi Virsa 2011 Melbourne Live",
            0,
        ),
        _t(
            "1kiQgBqaUA8r6a5Wmft08A",
            "Golay Rehnday",
            "Manmohan Waris",
            "Punjabi Virsa 2011 Melbourne Live",
            0,
        ),
        _t(
            "4A7bpdwEiVeV98OxbTiOwT",
            "Singh Rehnde Sada Chardi Kala",
            "Kuldeep Manak",
            "Singh Rehnde Sada Chardi Kala",
            0,
        ),
        _t("64UtBALf6GVeR2rcrP2L1a", "Paisee De Wajon", "Kuldeep Manak", "Paisee De Wajon", 0),
    ],
    "punjabi pop": [
        _t(
            "5zvZ1SeCcXcCWOp5NUeKGy",
            "Bhagat Muradaan Mangde",
            "Lovely Nirman",
            "Sohna Ae Darbar",
            0,
        ),
        _t(
            "1bpmFxK6hk2Fgpw4iCJq7Y",
            "Dhi Da Ni Dena Dola",
            "Kuldip Manak",
            "Heere Kachiye Jahan Diye",
            0,
        ),
        _t(
            "4A7bpdwEiVeV98OxbTiOwT",
            "Singh Rehnde Sada Chardi Kala",
            "Kuldeep Manak",
            "Singh Rehnde Sada Chardi Kala",
            0,
        ),
        _t("25jfDYiqYdX2pEDUBijSjT", "Kudi Koonj Wargi", "Sangtar", "Kudi Koonj Wargi", 0),
    ],
    "indian indie": [
        _t(
            "4Lp3zfbsLjgfd6iEGfsVZZ",
            "Hlimten ti ve mai la",
            "Lalrindiki Khiangte Daduhi",
            "Lengdun ila",
            0,
        ),
        _t(
            "788CD8RFUkwVQt9iROd8NM",
            "Fire By Stereo",
            "revel in the morning",
            "Fires Burn At Night",
            0,
        ),
        _t("4uS5H2prvyscJrlwm1Odn6", "Pirate", "revel in the morning", "God Less America", 0),
        _t(
            "5pBV43xqT2kx9A93FPxXS9",
            "God Less America",
            "revel in the morning",
            "God Less America",
            0,
        ),
    ],
    "hindustani classical": [
        _t(
            "6JcrLYDiRVA8aS25tDpjB3",
            "Kaise Basiya Bajaye",
            "Begum Akhtar",
            "Best of Begum Akhtar Ghazals Vol 1",
            0,
        ),
        _t("5q6wTpUJSyaVDWhEH2LQDk", "Sacred Calling", "Amaan Ali Bangash", "Truth", 0),
        _t(
            "18yfvK3iOBMZlKjocbzQqu",
            "Khuda Ki San",
            "Begum Akhtar",
            "Best of Begum Akhtar Ghazals Vol 6",
            0,
        ),
        _t("5x6p3K5kQRGKbrwOsnzmhv", "Meera Magan Bhaee", "Shobha Gurtu", "Hari Ke Goon Gavo", 0),
    ],
    "carnatic": [
        _t(
            "2JMSGz2yYFotUHKfYkhM82",
            "Ramanamamu",
            "Tyagaraja",
            "Hyderabad Sisters - Carnatic Classical",
            0,
        ),
        _t(
            "3lwcPGFVRBDkB4CmVQ7Vq9",
            "Tanam:Nadanamakriya:",
            "Jeyaraaj & Jaysri",
            "Anandam Anantam-A Journey into Tanam",
            0,
        ),
        _t(
            "6cIKYEKU3sEg5FWeFygglb",
            "Paripalayamam (Raga: Rithigowlam; Tala: Rupakam)",
            "Trichur V. Ramachandran",
            "Krithis Of Swathi Tirunal Vol. 1",
            0,
        ),
        _t(
            "5bb5hHThRr2AELtmfncgA3",
            "Vijayambike - Vijayanagari - Adi (Live)",
            "Sikkil Mala Chandrasekhar",
            "Collectors Choice Flute, Vol. 2 (Live)",
            0,
        ),
    ],
    "desi pop": [
        _t("7CJyd99TEHOAFf2UK8vgSf", "Shukriya", "B Praak", "Lock-Down Listening Sessions", 0),
        _t("6SzdrilYbkovQQApHzWewD", "Rabba Ve", "B Praak", "Lock-Down Listening Sessions", 0),
        _t(
            "56eKBGFUmcAUpXEwPtZqOZ",
            "Tu Bhi Sataya Jayega",
            "Vishal Mishra",
            "Best Of 2021 - (Heart Break Hits)",
            0,
        ),
        _t(
            "3l8Z0NiiaZZwSX1Ff4C8f6",
            'Aaj Mood Ishqholic Hai (From "Aaj Mood Ishqholic Hai")',
            "Meet Bros.",
            "Alco-Holiday - Weekend Special",
            0,
        ),
    ],
    "indian folk": [
        _t(
            "3wMw8xtv0g3mm5stgNTA4C",
            "Mauritius",
            "Indian Ocean",
            "Only Chillout (100% Selected Beats)",
            0,
        ),
        _t(
            "79yRC5SvBmZkd6zqdiApnh",
            "Ek Desh Ek Hum",
            "Dhruv Ghanekar",
            "Ek Desh Ek Hum - Single",
            0,
        ),
        _t(
            "1sd72yME0Ehcf7CyGH7xLq",
            "Aa Gayi Banke Sahara O Matarani",
            "Malini Awasthi",
            "Aa Gayi Banke Sahara O Matarani",
            0,
        ),
        _t("0fl2HOGE6bp0xaPGxiTLvo", "Bay of Bengal", "Indian Ocean", "Healing Energies", 0),
    ],
    "ghazal": [
        _t(
            "2ENHmd4fnHTP7EExcXcQbN",
            "Cholte Cholte Poth",
            "Runa Laila",
            "Golaguli (Original Motion Picture Soundtrack)",
            0,
        ),
        _t(
            "0uwL2gIaSiBPyVqEHxT1Mo",
            "Ei Boyoshe Moneri Dorja",
            "Runa Laila",
            "Rajpother Raja (Original Motion Picture Soundtrack)",
            0,
        ),
        _t(
            "0pKhXm0hjYqx8cIuFSspzz",
            "Michi Michi Dure Sore",
            "Runa Laila",
            "Ashar Alo (Original Motion Picture Soundtrack)",
            0,
        ),
        _t(
            "3m01EjQxI7WdKPUTXDcUUP",
            "Tumi Chile Na Tai Prem Chilo Na",
            "Runa Laila",
            "Prohori (Original Motion Picture Soundtrack)",
            0,
        ),
    ],
    "sufi": [
        _t(
            "6LHITF8NyMHo5scmvAyZfn",
            "Ek Munda Mere Muhalle Da",
            "Naseebo Lal",
            "Tera Mera Rishta Ki",
            0,
        ),
        _t("3EOJ7GAjeYWoHu3C2kqcQ3", "Mera Jisam Bloori", "Naseebo Lal", "Tera Mera Rishta Ki", 0),
        _t(
            "6I51k96LtnQj6jueZ2fkN8",
            "Mohabbat Hai Kiya",
            "Shazia Manzoor",
            "Mohabbat Hai Kiya Cheez (Pakistani Film Soundtrack)",
            0,
        ),
        _t(
            "1xxXsT4emslZGFOifpjrth",
            "Mera Ishq Vi Tun",
            "Naseebo Lal",
            "Rondoiyan Guzar Gai Rat",
            0,
        ),
    ],
    "filmi": [
        _t(
            "2DS6zjz76lPMISY6lSYNwp",
            "Gham Diya Mustaquil",
            "K. L. Saigal",
            "Raag Gao Raag Vol-1 & 2",
            0,
        ),
        _t(
            "5U9CAqH1R3Yf1xADVGOT1l",
            "Karunajuda Vamma - Varali - Misra Chapu(Live)",
            "Charulatha Mani",
            "Madrasil Margazhi - 2004 (Live)",
            0,
        ),
        _t("2d2htXr6qY7601JhMh3i3k", "Hai Yeh Kaisa Jahan", "Master Saleem", "Sai Mere", 0),
        _t("0X5I30cLLhGBT72FpWC8lO", "Patchaiyamma Patchaiyamma", "Mukesh", "Sakthi Arul", 0),
    ],
}

ARTIST_TOP_TRACKS_IN: dict[str, list[dict]] = {
    "Arijit Singh": [
        _t(
            "6WlARP6h4CDVOcY386wW0W",
            'Sitaare (From "Ikkis")',
            "Arijit Singh",
            'Sitaare (From "Ikkis")',
            0,
        ),
        _t("1awtp7rf6ajhGY9BgzCHeZ", "Darkhaast", "Mithoon", "Shivaay", 0),
        _t("0rk2X5TAhraBC5aCIXK2Rq", "Samjhawan", "Jawad Ahmad", "Samjhawan", 0),
        _t(
            "0Y6YW1552df031DjV8qBHv",
            'Gehra Hua (From "Dhurandhar")',
            "Shashwat Sachdev",
            'Gehra Hua (From "Dhurandhar")',
            0,
        ),
    ],
    "Pritam": [
        _t(
            "23T4WcVkvuaAEOgXr848i1",
            "Tera Mera Rishta - Original Version",
            "Pritam",
            "Awarapan (Original Motion Picture Soundtrack)",
            0,
        ),
        _t(
            "2cPUB8EOT6AfJ8oxhyoNXL",
            "Ye Tune Kya Kiya",
            "Pritam",
            "Once Upon Ay Time In Mumbai Dobaara !",
            0,
        ),
        _t("7eQl3Yqv35ioqUfveKHitE", "Tum Se Hi", "Pritam", "Jab We Met", 0),
        _t(
            "6LYfwNkkrplbxbheWtkBL2",
            'Toh Phir Aao - New Version (From "Awarapan 2")',
            "Mithoon",
            "Awarapan 2 (Original Motion Picture Soundtrack)",
            0,
        ),
    ],
    "Diljit Dosanjh": [
        _t("0XwRlvv3KlOu4HWlOH34XG", "Lover", "Diljit Dosanjh", "MoonChild Era", 0),
        _t(
            "50EDY0zGZteoBy3hORXSba",
            'Tere Paas Main - Female Version (From "Main Vaapas Aaunga")',
            "A.R. Rahman",
            "Main Vaapas Aaunga (Original Motion Picture Soundtrack)",
            0,
        ),
        _t(
            "7AAap8D4C4pTyNoMkM9vjG",
            "Ishq Di Baajiyaan",
            "Shankar-Ehsaan-Loy",
            "Soorma (Original Motion Picture Soundtrack [Deluxe Edition])",
            0,
        ),
        _t(
            "2aYExLSDUOwoUUj2qww6KU",
            'Sauda Khara Khara - From "Good Newwz"',
            "Diljit Dosanjh",
            "Artist Spotlight - Akshay Kumar",
            0,
        ),
        _t(
            "0rlvSn17z2CW62cM0EiWfl",
            "Ikk Kudi - Reprised Version",
            "Amit Trivedi",
            "Sunset & Strings",
            0,
        ),
    ],
    "Karan Aujla": [
        _t("0cYohCh24y1aMjJmcS9RBl", "For A Reason", "Karan Aujla", "P-POP CULTURE", 0),
        _t("3ExgWVPWOQts9RVBkqpdic", "Boyfriend", "Karan Aujla", "P-POP CULTURE", 0),
        _t("3FqtduiaqnFYvBgKuc6QWQ", "Winning Speech", "Karan Aujla", "Winning Speech", 0),
        _t("4CZl2BQkGPIFK99cf6jTAz", "Low Fade", "Karan Aujla", "Low Fade", 0),
        _t("4d2jV5fmX6hbRwaRbY39dt", "Wavy", "Karan Aujla", "Wavy", 0),
    ],
    "Prateek Kuhad": [
        _t("3hB9lDLyAClYVZivMMl20N", "Co2", "Prateek Kuhad", "The Way That Lovers Do", 0),
        _t("08kTa3SL9sV6Iy8KLKtGql", "Kasoor", "Prateek Kuhad", "Kasoor", 0),
        _t(
            "7nPCAO0Q9AHbM7PWyj9O98",
            "Kho Gaye Hum Kahan",
            "Jasleen Royal",
            "Baar Baar Dekho (Original Motion Picture Soundtrack)",
            0,
        ),
    ],
    "Anuv Jain": [
        _t(
            "1bMkimTb47umgNP6xCi4A1",
            "Arz Kiya Hai | Coke Studio Bharat",
            "Anuv Jain",
            "Arz Kiya Hai | Coke Studio Bharat",
            0,
        ),
        _t("0TL0LFcwIBF5eX7arDIKxY", "Husn", "Anuv Jain", "Husn", 0),
        _t("0eCajpR75pDW0r64U6hP2x", "Jo Tum Mere Ho", "Anuv Jain", "Jo Tum Mere Ho", 0),
        _t("4Qm7r3ImER8S2Ori1gLMAf", "Afsos", "Anuv Jain", "Afsos", 0),
        _t("3WLJ7D5kh44K5eJ1NqZQ6W", "Baarishein", "Anuv Jain", "Baarishein", 0),
    ],
    "A.R. Rahman": [
        _t("6flQ5XJKj5qIhpxSHOd3jC", "Aawaara Angaara", "A.R. Rahman", "Tere Ishk Mein", 0),
        _t("47RTQoh3pzjhWLUMllNRRJ", "Deewaana Deewaana", "A.R. Rahman", "Tere Ishk Mein", 0),
        _t(
            "5OMUXgfXsSukZ0zxelpC3b",
            'Raanjhanaa (From "Raanjhanaa")',
            "A.R. Rahman",
            "Raanjhanaa (Original Motion Picture Soundtrack)",
            0,
        ),
        _t(
            "4FeczSomVWVyU4FW7xDeAI",
            "Tere Bina",
            "A.R. Rahman",
            "Guru (Original Motion Picture Soundtrack)",
            0,
        ),
        _t(
            "1wnozUBSe7OMpmZiTPJC5j",
            'Tum Tak (From "Raanjhanaa")',
            "A.R. Rahman",
            "Raanjhanaa (Original Motion Picture Soundtrack)",
            0,
        ),
    ],
    "Shreya Ghoshal": [
        _t(
            "2y8mkajKikV5S1PRCMQ5WL",
            "KALYANI (with Shreya Ghoshal) - Remix",
            "ARJN",
            "KALYANI (with Shreya Ghoshal) [Remix]",
            0,
        ),
        _t("0rk2X5TAhraBC5aCIXK2Rq", "Samjhawan", "Jawad Ahmad", "Samjhawan", 0),
        _t(
            "3t3wsY5IdLVzB9WidegJSU",
            "Jeene Laga Hoon",
            "Sachin-Jigar",
            "Ramaiya Vastavaiya (Original Motion Picture Soundtrack)",
            0,
        ),
        _t("0xlWd9o8yjKpJ02WJy79kZ", "Tere Liye", "Atif Aslam", "Best of Romance: Atif Aslam", 0),
        _t(
            "2dDHtDrDaxTB7QR6EoCSne",
            "Saibo",
            "Sachin-Jigar",
            "Shor in the City (Original Motion Picture Soundtrack)",
            0,
        ),
    ],
    "DIVINE": [
        _t("4w3SKupiTNoAMi8JKbJAl9", "No Competition", "DIVINE", "No Competition", 0),
        _t("2gNMXJDKRmKWuevBGjN8wo", "3:59 AM", "DIVINE", "Punya Paap", 0),
        _t("3GEiVoaUXq468gfYs2EPfh", "Chorni", "DIVINE", "Chorni", 0),
        _t("4OigMohZdysiJr7oiwu1IL", "100 Million", "DIVINE", "Street Dreams", 0),
        _t("7tYAKbutuUrdxAhdOvqF01", "Nothing Lasts", "Karan Aujla", "Street Dreams", 0),
    ],
    "Ritviz": [
        _t("7tbzfR8ZvZzJEzy6v0d6el", "Liggi", "Ritviz", "Dev", 0),
        _t("7Gn4vU9RUHYV5aA1gMJSPV", "Pran", "Ritviz", "Dev", 0),
        _t("0YLSjVxSb5FT1Bo8Tnxr8j", "Baaraat", "Ritviz", "Baaraat", 0),
        _t("2nEntnpNpsJNhw1wLY8O96", "Jeet", "Ritviz", "Ved", 0),
        _t("43mHckutQvJr49nT0UvRxy", "Sage", "Ritviz", "Ved", 0),
    ],
}
